apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: rhtap-chatbot-app-33
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  rhtap-chatbot-app-33
    app.kubernetes.io/part-of: rhtap-chatbot-app-33-gitops  
  name: rhtap-chatbot-app-33
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  rhtap-chatbot-app-33 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  rhtap-chatbot-app-33
    spec:
      containers:
      - image: quay.io/redhat-appstudio/dance-bootstrap-app:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080 
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080 
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080 
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi    
        envFrom:
        - configMapRef:
            name: rhtap-chatbot-app-33-model-config
        env:
        - name: GIT_REPO
          value: https://github.com/mvaldron-rhdh/rhtap-chatbot-app-33-gitops
        - name: MODEL_ENDPOINT_BEARER
          valueFrom:
            secretKeyRef:
              name: model-bearer-secret
              key: API_KEY
      imagePullSecrets:
        - name: tssc-image-registry-auth
