apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-chatbot-app-33
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-chatbot-app-33 
  name: rhtap-chatbot-app-33
spec:
  ports:
  - port: 8080 
    targetPort: 8080 
  selector:
    app.kubernetes.io/instance: rhtap-chatbot-app-33 
